# Generated by Django 4.0 on 2022-11-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpassword',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
