# Generated by Django 4.0 on 2022-12-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='user_otp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
