# Generated by Django 4.0 on 2022-12-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0003_userverifiedmodel_delete_userotp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserVerifiedModel',
            new_name='UserVerified',
        ),
    ]
